### ISSUE TITLE
Pathfinder

### ISSUE THREAD

**Issue by strimper13** [chopshop-166/tasks#9]
[Pathfinder GitHub Official Repository](https://github.com/JacisNonsense/Pathfinder#part-of-the-first-robotics-competition)

-Software award here we come!

**Comment by msoucy** [comment]
[Pathfinder 2](https://github.com/GrappleRobotics/Pathfinder) is under development, but not released yet as far as I know. I recommend sticking to 1 for now.

I believe you can do it in `build.gradle` via:

```gradle
dependencies {
    compile pathfinder()
}
```

**Comment by msoucy** [comment]
I believe WPIlib is getting some more advanced kinematics for 2020. [Here](https://github.com/wpilibsuite/allwpilib/pull/1951) is a pull request that adds an example of usage. I'm going to say we should use that, instead of Pathfinder, as it'll (in theory) be officially supported. We can integrate commands using that class, if it doesn't get merged.
